// check item
export const DELETE_CHECKITEM = "DELETE_CHECKITEM";
export const SET_CHECKITEMS = "SET_CHECKITEMS";
export const LOAD_CHECKITEM_LIST = 'LOAD_CHECKITEM_LIST';
export const GET_CHECKITEM_LIST = 'GET_CHECKITEM_LIST';
export const CREATE_CHECKITEM = 'CREATE_CHECKITEM';
export const EDIT_CHECKITEM = 'EDIT_CHECKITEM';

// login
export const LOGIN = "LOGIN";
export const SET_USERINFO = "SET_USERINFO";

// project
export const SET_PROJECTS = "SET_PROJECTS";
export const LOAD_PROJECT_LIST = 'LOAD_PROJECT_LIST';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';

// token
export const SET_TOKEN_STATE = "SET_TOKEN_STATE";


//release
export const LOAD_RELEASE_LIST = 'LOAD_RELEASE_LIST';
export const GET_RELEASE_LIST = 'GET_RELEASE_LIST';
export const ADD_RELEASE = 'ADD_RELEASE';
export const REVISE_RELEASE = 'REVISE_RELEASE' 
export const LOAD_RELEASE_DETAIL = 'LOAD_RELEASE_DETAIL';
export const GET_RELEASE_DETAIL = 'GET_RELEASE_DETAIL'
export const EDIT_RELEASE = 'EDIT_RELEASE';
export const PUBLISH_RELEASE = 'PUBLISH_RELEASE';
export const DELETE_RELEASE = 'DELETE_RELEASE';
